name: InfectedAddon-DedicatedServer
description: Infected Dedicated Server Addon
main: me.sniperzciinema.infectedaddon.dedicatedserver.Main
version: 0.2
author: xXSniperzzXx_SD
depend: [Infected]