# InfectedAddon-Ranks default config, last edited in 0.0.2
# If "Use score for ranks" is false it'll use points instead
# ################################################# #
Use score for ranks: true