name: Infected
main: me.sniperzciinema.infected.Infected
author: SniperzCiinema
version: 2.2.0
description: MW3 Infected for Minecraft!
softdepend: [DisguiseCraft, iDisguise, LibsDisguises, Vault, Factions, mcMMO]
website: www.youtube.com/user/SniperzCiinema
commands:
  Infected:
    description: Infected's Basic Command
    usage: /<command>
    aliases: [/i, inf]
    
    
permissions:
# Default permissions given to everyone  
  Infected.Default:
    default: true
    children:
      Infected.Join: true
      Infected.Leave: true
      Infected.Vote: true
      Infected.Classes: true
      Infected.Shop: true
      Infected.Grenades: true
      Infected.List: true
      Infected.Chat: true
      Infected.Stats: true
      Infected.Suicide: true
      Infected.Info: true
      Infected.Top: true
      Infected.Arenas: true
      Infected.Stats.Other: true
      Infected.Classes.*: true
      Infected.CmdSets: true
      
  Infected.Signs.*:
    default: op
    children:
      Infected.Signs.Shop: true
      Infected.Signs.Info: true
      Infected.Signs.Command: true
      Infected.Signs.CmdSet: true
      Infected.Signs.Classes: true
      
# Permission nodes for setting up an arena      
  Infected.Setup:
    default: op
    children:
      Infected.TpLobby: true
      Infected.TpLeave: true
      Infected.SetLobby: true
      Infected.SetLeave: true
      Infected.SetSpawn: true
      Infected.Spawns: true
      Infected.TpSpawn: true
      Infected.DelSpawn: true
      Infected.SetArena: true
      Infected.Create: true
      Infected.Remove: true
      Infected.SetClass: true
      Infected.Signs.*: true
      
# Permission nodes needed to do the admin commands      
  Infected.Admin:
    default: op
    children:
      Infected.Files: true
      Infected.Admin.Points: true
      Infected.Admin.Score: true
      Infected.Admin.Kills: true
      Infected.Admin.Deaths: true
      Infected.Admin.Kick: true
      Infected.Admin.Shutdown: true
      Infected.Admin.Reload: true
      Infected.Admin.Code: true
      Infected.Start: true
      Infected.Stop: true
      Infected.Setup: true
      
# Infected.Stats.Other will also give you perms to look at your own stats
  Infected.Stats.Other:
    default: false
    children:
      Infected.Stats: true

# Infected.Chat.Spy also provides perms to chat  
  Infected.Chat.Spy:
    default: false
    children:
      Infected.Chat: true
      
# Infected.Classes provides ALL class perms      
  Infected.Classes.*:
    default: true
    children:
      Infected.Classes.Human: true
      Infected.Classes.Zombie: true
      
# Infected.* provides ALL Infected's Permissions      
  Infected.*:
    default: op
    children:
      Infected.Default: true
      Infected.Admin: true